<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>Ping.Api</AssemblyName>
    <RootNamespace>Ping.Api</RootNamespace>
    <UserSecretsId>ed416956-761d-4ded-8424-fc612ea6803c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Ping.Application\Ping.Application.csproj" />
    <ProjectReference Include="..\..\Core\Ping.Domain\Ping.Domain.csproj" />
    <ProjectReference Include="..\..\Core\Ping.Infrastructure\Ping.Infrastructure.csproj" />
  </ItemGroup>

</Project>
